import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
const base=process.env.TEST_URL||'http://127.0.0.1:3000';
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
mkdirSync('screenshots',{recursive:true});
try{
 await page.goto(base);await page.getByRole('heading',{name:'Chào Judy, một ngày làm việc mới.'}).waitFor();
 await page.screenshot({path:'screenshots/01-overview.png',fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'Khách hàng',exact:true}).click();
 await page.getByRole('button',{name:'Tạo khách hàng',exact:true}).click();
 await page.getByLabel('Tên khách hàng',{exact:false}).fill('Demo Review');
 await page.getByLabel('Công ty / Salon').fill('Review Hair Studio');
 await page.getByLabel('Điện thoại / WhatsApp').fill('+1 202 555 0199');
 await page.getByLabel('Email hoặc tên đăng nhập',{exact:true}).fill('review@example.com');
 await page.getByLabel('Mạng xã hội / Trang web hoặc WhatsApp').fill('https://example.com');
 await page.getByRole('button',{name:'Dùng thông tin khách hàng'}).click();
 await page.getByLabel('Địa chỉ giao hàng').fill('123 Demo Street, Sample City');
 await page.getByRole('button',{name:'Lưu khách hàng',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Demo Review',exact:true}).click();
 await page.getByRole('button',{name:'Tạo đơn',exact:true}).click();
 await page.getByLabel('Dự kiến giao hàng').fill('2026-10-20');
 await page.getByLabel('Số lượng 1').fill('200');
 await page.screenshot({path:'screenshots/02-order-form.png',fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'Lưu bản nháp',exact:true}).first().click();
 await page.getByRole('heading',{name:/HQ-JD-9-1/}).waitFor();
 assert.equal(await page.getByRole('heading',{name:'Tiến độ đơn hàng'}).count(),0);
 await page.reload();await page.getByRole('heading',{name:'Chào Judy'}).waitFor();
 await page.locator('nav').getByRole('button',{name:/Đơn hàng/}).click();
 await page.getByRole('button',{name:'HQ-JD-9-1',exact:true}).click();
 await page.getByRole('button',{name:'Chỉnh sửa',exact:true}).click();
 await page.getByRole('button',{name:'Thanh toán & giao hàng',exact:true}).last().click();
 await page.getByLabel('Giảm giá (USD)').fill('50');
 await page.getByLabel('Phí vận chuyển (USD)').fill('60');
 await page.getByLabel('Phí nhận tiền (USD)').fill('10');
 await page.getByRole('button',{name:'Gửi yêu cầu duyệt'}).click();
 await page.getByRole('heading',{name:'Tiến độ đơn hàng'}).waitFor();
 await page.getByRole('button',{name:'Xin quyền chỉnh sửa'}).waitFor();
 await page.getByRole('button',{name:'Thanh toán & giao hàng',exact:true}).click();
 await page.getByRole('button',{name:'Bổ sung',exact:true}).click();
 await page.getByLabel('Số tiền dự kiến (USD) · không bắt buộc').fill('500');
 await page.getByLabel('Mã giao dịch').fill('DEMO-TEST');
 await page.getByRole('button',{name:'Thêm thanh toán',exact:true}).click();
 await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByText('Chờ xác nhận',{exact:true}).waitFor();
 await page.getByLabel('Nội dung trao đổi').fill('Demo kiểm tra đơn hàng.');
 await page.getByRole('button',{name:'Gửi',exact:true}).click();
 await page.getByText('Demo kiểm tra đơn hàng.',{exact:true}).waitFor();
 await page.screenshot({path:'screenshots/03-order-detail.png',fullPage:true,animations:'disabled'});
 const state=await (await context.request.get(base+'/api/state')).json();const order=state.orders.find(o=>o.id==='HQ-JD-9-1');
 assert.equal(order.stage,2);assert.equal(order.payments[0].confirmed,false);
 const forbidden=await context.request.post(base+'/api/orders',{data:{...order,note:'bypass lock'}});assert.equal(forbidden.status(),400);
 const other=await browser.newContext();const separate=await(await other.request.get(base+'/api/state')).json();assert(!separate.orders.some(o=>o.id==='HQ-JD-9-1'));await other.close();
 await page.getByRole('button',{name:'In hóa đơn'}).click();await page.getByText('COMMERCIAL INVOICE').waitFor();
 await page.screenshot({path:'screenshots/04-invoice.png',fullPage:true,animations:'disabled'});
 await page.emulateMedia({media:'print'});await page.pdf({path:'screenshots/invoice.pdf',format:'A4'});await page.emulateMedia({media:'screen'});
 await page.getByRole('button',{name:'Đóng',exact:true}).click();
 await page.getByRole('button',{name:'Doanh thu & công nợ',exact:true}).click();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Xuất báo cáo CSV'}).click();assert((await download).suggestedFilename().endsWith('.csv'));
 await page.screenshot({path:'screenshots/05-revenue.png',fullPage:true,animations:'disabled'});
 assert.deepEqual(errors,[]);console.log('PASS: customer creation, draft persistence, submit/lock, pending receipt, chat, session isolation, invoice and CSV export.');
}finally{await browser.close()}
