import {canForfeitPaused} from '../accounting.js';
import {OrderAttention} from './order-attention.jsx';
import {OrderTimeline} from './order-timeline.jsx';
import {orderLabel} from '../order-identity.js';
import React,{useEffect,useState} from 'react';
import {workspaceAPI} from './workspace-access.jsx';
import {totals,money,status} from '../shared.js';
import {paymentLabels} from '../accounting.js';
import {QualityControl} from './quality-control.jsx';
import {ProductReadTable} from './product-table.jsx';
import './quality-control.css';

export function AccountingWorkspace({user,onLogout,Payments}){
 const [data,setData]=useState(null),[id,setId]=useState(''),[filter,setFilter]=useState('pending'),[tab,setTab]=useState(1),[receipts,setReceipts]=useState({}),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[version,setVersion]=useState(null),[confirm,setConfirm]=useState(null);
 const load=async()=>{const d=await workspaceAPI('/state');setData(d);return d};
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(id)return;let alive=true;const refresh=()=>workspaceAPI('/state').then(d=>{if(alive)setData(d)}).catch(()=>{});const timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);return()=>{alive=false;clearInterval(timer);window.removeEventListener('focus',refresh)}},[id]);
 const order=data?.orders.find(o=>o.id===id),total=order&&totals(order);
 const pausedException=order&&canForfeitPaused(order);
 const finalStage=order&&[6,7].includes(order.stage);
 const select=o=>{setId(o.id);setVersion(o.version);setReceipts({});setNote('');setConfirm(null);setError('');setTab(1)};
 const decide=async()=>{
  setBusy(true);setError('');
  try{const next=await workspaceAPI(`/orders/${id}/action`,{version,action:({cancel:'accounting-cancel',final:'accounting-final',forfeit:'accounting-forfeit'})[confirm]||'accounting-approve',paymentStatus:confirm,text:note,receipts:Object.entries(receipts).map(([id,amount])=>({id,amount:Number(amount)}))});setData(next);setVersion(next.orders.find(o=>o.id===id).version);setReceipts({});setConfirm(null)}catch(e){setError(e.message)}finally{setBusy(false)};
 };
 return <div className="factory-shell accounting-shell"><header className="factory-header"><div className="brand"><span className="brand-mark">HQ</span><span>HQ HAIR<small>KHÔNG GIAN KẾ TOÁN</small></span></div><span>{user.name} <button className="btn" onClick={onLogout}>Đăng xuất</button></span></header><main>
 <div className="page-title"><div><h1>{order?orderLabel(order):'Kế toán duyệt đơn'}</h1><p>Đối soát chứng từ và xác nhận số tiền thực nhận tại bước 3 và bước 7.</p></div><div className="actions">{order&&<button className="btn" onClick={()=>{setId('');setConfirm(null)}}>Danh sách đơn</button>}<button className="btn" disabled={busy} onClick={async()=>{try{const d=await load();if(id){const o=d.orders.find(o=>o.id===id);if(o)select(o)}}catch(e){setError(e.message)}}}>Tải dữ liệu mới</button></div></div>
 {error&&<p className="access-error" role="alert">{error}</p>}
 {data&&!order&&<OrderAttention data={data} onOpen={select}/>}{!data?<p>Đang tải…</p>:!order?<section className="panel"><div className="filters"><label>Hiển thị <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">Chờ Kế toán duyệt</option><option value="approved">Đã duyệt</option><option value="cancelled">Đã hủy</option><option value="all">Tất cả đơn đã gửi</option></select></label></div><table><thead><tr><th>Đơn hàng</th><th>Sale</th><th>Trạng thái</th><th>Phải nhận</th><th>Đã nhận</th><th>Công nợ</th></tr></thead><tbody>{data.orders.filter(o=>filter==='all'||filter==='pending'&&([6,7].includes(o.stage)||o.stage===2||canForfeitPaused(o))||filter==='approved'&&o.accountingApproval||filter==='cancelled'&&o.cancelledAt).map(o=><tr key={o.id}><td><button className="order-link" onClick={()=>select(o)}>{orderLabel(o)}</button></td><td>{o.sale}</td><td>{status(o)}<small>{paymentLabels[o.accountingApproval?.status]}</small></td><td>{money(totals(o).receive)}</td><td>{money(totals(o).paid)}</td><td>{o.cancelledAt?'—':money(totals(o).debt)}</td></tr>)}</tbody></table></section>:<>
 <OrderTimeline order={order}/>
 {order.cancelledAt&&<div className="notice">Đã hủy đơn · {order.cancelReason}</div>}
 <section className="panel"><div className="tabs">{[[1,'Sản phẩm'],[2,'Thanh toán & giao hàng'],[3,'Phiếu kiểm định']].map(([n,label])=><button key={n} className={tab===n?'selected':''} onClick={()=>setTab(n)}>{label}</button>)}</div>
 {tab===1?<ProductReadTable items={order.items}/>:tab===3?<QualityControl order={order} user={user}/>:<div className="panel-body"><div className="profile-info">{[['Khách',data.customers.find(c=>c.id===order.customerId)?.name],['Người nhận',order.recipient],['Địa chỉ',order.address],['Điện thoại',order.phone],['Vận chuyển',order.carrier],['Mã vận đơn',order.tracking]].map(([k,v])=><div key={k}><small>{k}</small><b>{v||'—'}</b></div>)}</div><Payments order={order}/></div>}</section>
 <section className="panel panel-body"><h2>{finalStage||pausedException||order.finalPaymentCheck?'7. Kiểm tra thanh toán lần cuối':'3. Đã duyệt'}</h2>{order.accountingApproval&&<p className="notice">{paymentLabels[order.accountingApproval.status]} · {order.accountingApproval.name} · {new Date(order.accountingApproval.time).toLocaleString('vi-VN')}</p>}<div className="qc-summary"><span>Phải nhận <b>{money(total.receive)}</b></span><span>Đã xác nhận <b>{money(total.paid)}</b></span><span>Còn nợ <b>{order.cancelledAt?'—':money(total.debt)}</b></span></div>
 {([2,6,7].includes(order.stage)||pausedException)&&!order.cancelledAt&&<><p>Chọn chứng từ đã đối soát và nhập số tiền thực nhận. Khoản đã xác nhận trước đó được giữ nguyên.</p><Payments order={order}/><div className="accounting-receipts">{order.payments.filter(p=>!p.confirmed).map(p=><label key={p.id} className="field"><span><input type="checkbox" checked={Object.hasOwn(receipts,p.id)} onChange={e=>{const next={...receipts};if(e.target.checked)next[p.id]=p.amount||'';else delete next[p.id];setReceipts(next);setConfirm(null)}}/> {p.sender} · {p.method} · {p.reference||p.date}</span>{Object.hasOwn(receipts,p.id)&&<input aria-label={'Thực nhận '+p.id} type="number" min="0.01" max="10000000" step="0.01" value={receipts[p.id]} onChange={e=>{setReceipts({...receipts,[p.id]:e.target.value});setConfirm(null)}}/>}</label>)}</div>{!order.payments.length&&<p className="muted">Chưa có chứng từ. Sale cần bổ sung chứng từ trước khi Kế toán xác nhận thanh toán.</p>}<label className="field"><span>Ghi chú / Lý do hủy</span><textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="actions">{finalStage||pausedException?<><button className="btn primary" disabled={busy||pausedException||(total.debt>0&&!Object.keys(receipts).length)} onClick={()=>setConfirm('final')}>Xác nhận đủ</button><button className="btn danger" disabled={busy||total.paid<=0||total.debt<=0} onClick={()=>setConfirm('forfeit')}>Hủy đơn mất cọc</button></>:<><button className="btn danger" disabled={busy||!!order.payments.length||!!order.accountingApproval} onClick={()=>setConfirm('cancel')}>Hủy đơn</button>{Object.entries(paymentLabels).map(([key,label])=><button key={key} className="btn primary" disabled={busy||!Object.keys(receipts).length} onClick={()=>setConfirm(key)}>{label}</button>)}</>}</div>{confirm&&<div className="notice"><div><p>{confirm==='forfeit'?'Hủy đơn mất cọc và đóng hoàn thành ngay? Mã đơn, tiền đã nhận và chứng từ được giữ nguyên.':confirm==='final'?'Xác nhận đã thu đủ tiền và chuyển Sale kiểm định, đặt ship?':confirm==='cancel'?'Xác nhận hủy đơn chưa có thanh toán?':`Xác nhận ${paymentLabels[confirm].toLowerCase()} với ${money(Object.values(receipts).reduce((sum,n)=>sum+Number(n||0),0))} thực nhận bổ sung?`}</p><button className="btn" disabled={busy} onClick={()=>setConfirm(null)}>Quay lại</button> <button className="btn primary" disabled={busy||['cancel','forfeit'].includes(confirm)&&!note.trim()} onClick={decide}>Xác nhận {['cancel','forfeit'].includes(confirm)?'hủy đơn':'duyệt'}</button></div></div>}</>}
 </section></>}
 </main></div>;
}
