import React,{useState,useEffect} from 'react';
import {money,dateText,today} from '../shared.js';
import {compensationTotal} from '../compensation-totals.js';
export function Compensation({order,user,busy,onAction,draftStatus,readOnly}){
 const [amount,setAmount]=useState(''),[date,setDate]=useState(today()),[note,setNote]=useState('');
 const editable=!readOnly&&!!order.orderCode&&order.stage>=3&&['sale','manager','sales_lead'].includes(user?.role||'sale');
 useEffect(()=>{if(draftStatus)draftStatus.current=!!(amount||note);return()=>{if(draftStatus)draftStatus.current=false}},[amount,note,draftStatus]);
 const submit=async e=>{e.preventDefault();if(await onAction(order.id,'compensation-add',{amount,date,text:note})){setAmount('');setNote('')}};
 return <div className="panel-body"><h3>Bồi thường / hoàn hàng</h3><p className="muted">Ghi nhận tiền thiệt hại do bồi thường hoặc hoàn hàng (USD). Khoản này được cộng vào ô Thiệt hại; công nợ và tiền đã thu được theo dõi riêng.</p><p className="section-label">Tổng thiệt hại: <strong>{money(compensationTotal(order))}</strong></p>{editable?<form onSubmit={submit}><div className="form-grid"><label className="field"><span>Tiền bồi thường (USD) *</span><input aria-label="Tiền bồi thường (USD)" type="number" min="0.01" max="10000000" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field"><span>Ngày ghi nhận *</span><input type="date" required min={order.date} max={today()} value={date} onChange={e=>setDate(e.target.value)}/></label></div><label className="field"><span>Lý do bồi thường / hoàn hàng *</span><textarea required maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="btn primary" disabled={busy} type="submit">Ghi nhận bồi thường</button></form>:!order.orderCode&&<p className="notice">Có thể ghi nhận bồi thường sau khi đơn được duyệt.</p>}<div className="audit">{(order.compensations||[]).slice().reverse().map(entry=><div key={entry.id}><b>{money(entry.amount)}{entry.voidedAt?' · Đã hủy ghi nhận':''}</b><small>{dateText(entry.date)} · {entry.name}</small><p style={{whiteSpace:'pre-wrap'}}>{entry.note}</p>{entry.voidedAt?<p>Lý do hủy: {entry.voidReason}</p>:editable&&(user?.role==='manager'||entry.by===user?.id)&&<button className="btn" disabled={busy} onClick={()=>{const text=window.prompt('Lý do hủy ghi nhận bồi thường:');if(text?.trim())onAction(order.id,'compensation-void',{entryId:entry.id,text})}}>Hủy ghi nhận</button>}</div>)}</div>{!order.compensations?.length&&<p className="inline-empty">Chưa có khoản bồi thường.</p>}</div>
}
