import React,{useState} from 'react';
import {countries,groups} from '../shared.js';
import {purchaseHistory,cleanCustomer} from '../customer-fields.js';
import {displayLabel} from './display-labels.js';
export function CustomerForm({customer,orders,busy,onClose,onSave,Modal}){
 const [c,setC]=useState({name:'',company:'',phone:'',email:'',country:'',group:'',address:'',recipient:'',recipientPhone:'',recipientEmail:'',shippingCountry:customer?.country||'',social:'',website:'',source:'',...customer}),[error,setError]=useState('');
 const set=(key,value)=>setC(v=>({...v,[key]:value}));
 const field=(key,label,required=false,type='text')=><label className="field"><span>{label}{required?' *':''}</span><input type={type} required={required} value={c[key]||''} onChange={e=>set(key,e.target.value)} maxLength={500}/></label>;
 const select=(key,label,values)=><label className="field"><span>{label} *</span><select required value={c[key]} onChange={e=>set(key,e.target.value)}><option value="">Chọn {label.toLowerCase()}</option>{values.map(v=><option key={v} value={v}>{displayLabel(v)}</option>)}</select></label>;
 return <Modal title={customer?'Chỉnh sửa hồ sơ khách hàng':'Tạo khách hàng mới'} onClose={onClose} wide><form onSubmit={e=>{e.preventDefault();try{cleanCustomer(c,customer);setError('');onSave(c)}catch(e){setError(e.message)}}}><div className="modal-body"><div className="two-col"><section><h3>Thông tin khách hàng</h3><p className="muted">Bắt buộc nhập ít nhất tên khách hàng hoặc công ty.</p>{field('name','Tên khách hàng',!c.company.trim())}{field('company','Công ty / Salon',!c.name.trim())}{field('phone','Điện thoại / WhatsApp',true,'tel')}{field('email','Email',false,'email')}{select('group','Phân loại',groups)}{select('source','Nguồn khách',['Instagram','Website','WhatsApp','Facebook','Giới thiệu','Khác'])}{field('social','Mạng xã hội')}{field('website','Trang web',false,'url')}<p className="muted">Không bắt buộc. Nếu nhập, dùng link đầy đủ https://…</p>{select('country','Quốc gia khách hàng',countries)}</section><section><h3>Thông tin giao hàng</h3><button type="button" className="text-btn copy-contact" onClick={()=>setC({...c,recipient:c.name||c.company,recipientPhone:c.phone,recipientEmail:c.email,shippingCountry:c.country})}>Dùng thông tin khách hàng</button>{field('recipient','Tên người nhận',true)}{field('recipientPhone','Điện thoại người nhận',true,'tel')}{field('recipientEmail','Email người nhận',false,'email')}{select('shippingCountry','Quốc gia giao hàng',countries)}<label className="field"><span>Địa chỉ giao hàng *</span><textarea required rows={3} value={c.address} onChange={e=>set('address',e.target.value)}/></label><label className="field"><span>Lịch sử mua hàng · tự động</span><input readOnly value={purchaseHistory(customer?.id,orders)}/></label><p className="muted">Tính từ đơn đã được Kế toán duyệt. Đổi hồ sơ không thay đổi thông tin giao hàng trên đơn cũ.</p></section></div>{error&&<p role="alert" className="form-error">{error}</p>}</div><div className="modal-footer"><button type="button" className="btn" onClick={onClose}>Hủy</button><button className="btn primary" disabled={busy}>{busy?'Đang lưu…':'Lưu khách hàng'}</button></div></form></Modal>;
}
