import React,{useState,useEffect} from 'react';
import {Package,Clock,CheckCircle,Truck,ArrowRight} from '@phosphor-icons/react';
import {factoryTabs,factoryOrders,factoryGroup,factoryState,factoryStateLabels,filterFactoryOrders,quantityText,factoryReport,recordedAt,checkAt,waitingDays} from '../factory-model.js';
import {deliveryTiming,deliveryDate} from '../delivery-days.js';
import {today,dateText} from '../shared.js';
import {OrderNotifications} from './order-notifications.jsx';

const groupIcons={waiting:Clock,production:Package,review:CheckCircle,office:Truck};
const states={waiting:[],production:['producing','paused','forfeited','fee_forfeited','cancelled'],review:['waiting_review','accepted','rework'],office:['payment','shipped']};
function Timing({order}){const t=deliveryTiming(order);return <span className={'badge '+t.tone}>{t.detail}</span>}
function Bars({rows,field,label}){const max=Math.max(1,...rows.map(r=>r[field]));return <div className="factory-bars" role="img" aria-label={label}>{rows.map(r=><div key={r.month}><span>{Number(r[field].toFixed(2))}</span><i style={{height:`${Math.max(2,r[field]/max*130)}px`}}/><small>T{Number(r.month.slice(5))}</small></div>)}</div>}
export function FactoryBoard({data,tab,onTab,onOpen,onBatch,busy}){
 const [query,setQuery]=useState(''),[state,setState]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[dueFrom,setDueFrom]=useState(''),[dueTo,setDueTo]=useState(''),[urgency,setUrgency]=useState('all'),[sort,setSort]=useState('due'),[timing,setTiming]=useState('all'),[page,setPage]=useState(1),[selected,setSelected]=useState([]),[choice,setChoice]=useState(null),[note,setNote]=useState(''),[year,setYear]=useState(today().slice(0,4)),[month,setMonth]=useState('all'),[overviewMonth,setOverviewMonth]=useState(today().slice(0,7));
 useEffect(()=>{setState('all');setPage(1);setSelected([]);setChoice(null);setFrom('');setTo('');setDueFrom('');setDueTo('');setUrgency('all');setTiming('all');setQuery('')},[tab]);
 useEffect(()=>{setSelected([]);setChoice(null)},[query,state,from,to,dueFrom,dueTo,urgency,sort,timing]);
 const orders=factoryOrders(data.orders),counts=Object.fromEntries(Object.keys(groupIcons).map(key=>[key,orders.filter(o=>factoryGroup(o)===key).length]));
 const chartOrders=orders.filter(o=>!overviewMonth||deliveryDate(o.date).startsWith(overviewMonth)),chartCounts=Object.fromEntries(Object.keys(groupIcons).map(key=>[key,chartOrders.filter(o=>factoryGroup(o)===key).length]));
 const filtered=filterFactoryOrders(orders,{tab,query,state,from,to,dueFrom,dueTo,urgency,sort,timing}),pages=Math.max(1,Math.ceil(filtered.length/12)),currentPage=Math.min(page,pages),visible=filtered.slice((currentPage-1)*12,currentPage*12);
 const change=(fn,value)=>{fn(value);setPage(1)};
 const toggle=id=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const candidate=rows=>rows.filter(o=>!o.cancelledAt&&!o.contentLockedAt&&[3,4].includes(o.stage));
 const start=(action,status,rows)=>{setChoice({action,status,orders:rows.map(o=>({id:o.id,version:o.version})),label:action==='factory-office'?'Gửi văn phòng':status==='producing'?'Ghi nhận / tiếp tục sản xuất':status==='paused'?'Tạm dừng':'Gửi Sale Check'});setNote('')};
 const selection=filtered.filter(o=>selected.includes(o.id));
 const available=selection.length>0&&selection.length<=100&&candidate(selection).length===selection.length;
 const yearRows=factoryReport(orders,year).map(r=>({...r,kg:r.grams/1000})),report=yearRows.filter(r=>month==='all'||r.month===month);
 const sum=key=>report.reduce((s,r)=>s+r[key],0),known=sum('early')+sum('onTime')+sum('late');
 const years=[...new Set([today().slice(0,4),...orders.map(o=>deliveryDate(o.officeDispatch?.time).slice(0,4)).filter(Boolean)])].sort().reverse();
 const table=(rows,compact=false)=><div className="table-scroll"><table className="factory-order-table"><thead><tr>{!compact&&<th><input aria-label="Chọn tất cả trên trang" type="checkbox" checked={candidate(rows).length>0&&candidate(rows).every(o=>selected.includes(o.id))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...candidate(rows).map(o=>o.id)])]:selected.filter(id=>!rows.some(o=>o.id===id)))}/></th>}<th>Mã đơn / Sale</th><th>Sản lượng</th><th>{tab==='production'?'Ngày ghi nhận':tab==='review'?'Ngày gửi Sale Check':tab==='office'?'Ngày gửi văn phòng':'Ngày đặt'}</th><th>Hạn gửi văn phòng</th><th>Trạng thái</th><th>Tiến độ</th>{tab==='review'&&<><th>Chờ Sale</th><th>Phản hồi Sale</th></>}<th>Thao tác</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}>{!compact&&<td><input aria-label={`Chọn ${o.orderCode}`} type="checkbox" disabled={!candidate([o]).length||busy} checked={selected.includes(o.id)} onChange={()=>toggle(o.id)}/></td>}<td><button className="order-link" onClick={()=>onOpen(o)}>{o.orderCode}</button><small>{o.sale}</small></td><td>{quantityText(o)}</td><td>{dateText(deliveryDate(tab==='production'?recordedAt(o):tab==='review'?checkAt(o):tab==='office'?o.officeDispatch?.time:o.date))}</td><td>{dateText(deliveryTiming(o).due)}</td><td><span className={'badge '+(o.cancelledAt?'red':o.production?.status==='paused'?'amber':'blue')}>{factoryStateLabels[factoryState(o)]}</span></td><td><Timing order={o}/></td>{tab==='review'&&<td>{o.stage===5&&waitingDays(o)!=null?`${waitingDays(o)} ngày`:'—'}</td>}{tab==='review'&&<td className="factory-feedback">{o.saleReview?.note||'—'}<small>{o.saleReview?.name} {o.saleReview?.time?dateText(deliveryDate(o.saleReview.time)):''}</small></td>}<td><button className="btn" onClick={()=>onOpen(o)}>Chi tiết</button>{!compact&&o.stage===3&&!o.cancelledAt&&<button className="btn primary" disabled={busy} onClick={()=>start('factory-status','producing',[o])}>Ghi nhận</button>}</td></tr>)}</tbody></table>{!rows.length&&<p className="empty">Không có đơn phù hợp.</p>}</div>;
 return <>
 <div className="page-title"><div><span className="factory-eyebrow">HQ HAIR / SẢN XUẤT</span><h1>{factoryTabs[tab]}</h1><p>{tab==='overview'?'Theo dõi sản xuất và phối hợp với Sale trong cùng một hệ thống.':tab==='analytics'?'Theo ngày thực tế gửi văn phòng. Gram quy đổi sang kg; các đơn vị khác được thống kê riêng.':`${filtered.length} đơn · Chỉ bao gồm đơn đã được Kế toán duyệt.`}</p></div><span className="badge blue">{dateText(today())}</span></div>
 {tab==='overview'?<>
 <div className="factory-kpis">{Object.entries(groupIcons).map(([key,Icon])=><button className="panel factory-kpi" key={key} onClick={()=>onTab(key)}><span>{factoryTabs[key]}<Icon size={24}/></span><strong>{counts[key]}</strong><small>Xem danh sách <ArrowRight/></small></button>)}</div>
 <div className="factory-overview-grid"><section className="panel"><div className="panel-head"><h3>Đơn theo trạng thái hiện tại</h3></div><div className="panel-body factory-state-bars"><input aria-label="Tháng đặt hàng" type="month" value={overviewMonth} onChange={e=>setOverviewMonth(e.target.value)}/><small> Theo tháng đặt hàng</small>{Object.keys(groupIcons).map(key=><button key={key} onClick={()=>onTab(key)}><span>{factoryTabs[key]}<b>{chartCounts[key]}</b></span><i style={{width:`${Math.max(1,chartCounts[key]/Math.max(1,chartOrders.length)*100)}%`}}/></button>)}</div></section><section className="panel factory-news"><div className="panel-head"><h3>Thông báo mới</h3></div><OrderNotifications data={{...data,orders}} onOrder={onOpen}/></section></div>
 <section className="panel"><div className="panel-head"><div><h3>Đơn cần ưu tiên</h3><small>Chưa gửi văn phòng · quá hạn hoặc còn tối đa 3 ngày</small></div></div>{table(orders.filter(o=>!o.cancelledAt&&!o.officeDispatch&&o.stage<6&&deliveryTiming(o).days!=null&&deliveryTiming(o).days<=3).sort((a,b)=>deliveryTiming(a).days-deliveryTiming(b).days).slice(0,10),true)}</section>
 </>:tab==='analytics'?<>
 <div className="filters"><label>Năm <select aria-label="Năm thống kê" value={year} onChange={e=>{setYear(e.target.value);setMonth('all')}}>{years.map(y=><option key={y}>{y}</option>)}</select></label><label>Tháng <select aria-label="Tháng thống kê" value={month} onChange={e=>setMonth(e.target.value)}><option value="all">Cả năm</option>{yearRows.map(r=><option key={r.month} value={r.month}>{r.month}</option>)}</select></label></div>
 <div className="factory-kpis">{[['Đã gửi văn phòng',sum('total')],['Sớm',sum('early')],['Đúng hạn',sum('onTime')],['Trễ',sum('late')]].map(([label,n])=><div className="panel factory-kpi" key={label}><span>{label}</span><strong>{n}</strong><small>{label==='Đã gửi văn phòng'?`${sum('unknown')} đơn thiếu dữ liệu tiến độ`:known?`${(n/known*100).toFixed(1)}% số đơn đủ dữ liệu`:'Chưa có dữ liệu'}</small></div>)}</div>
 <div className="factory-overview-grid"><section className="panel panel-body"><h3>Số đơn gửi văn phòng theo tháng</h3><Bars rows={yearRows} field="total" label="Số đơn theo tháng"/></section><section className="panel panel-body"><h3>Sản lượng theo tháng (kg)</h3><Bars rows={yearRows} field="kg" label="Sản lượng gram quy đổi kg theo tháng"/></section></div>
 <section className="panel"><div className="panel-head"><h3>Bảng tổng hợp</h3></div><div className="table-scroll"><table><thead><tr>{['Tháng','Tổng đơn','Sớm','Đúng hạn','Trễ','Chưa rõ','Tỷ lệ đúng tiến độ','Sản lượng'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{report.map(r=><tr key={r.month}><td>{r.month}</td><td>{r.total}</td><td>{r.early}</td><td>{r.onTime}</td><td>{r.late}</td><td>{r.unknown}</td><td>{r.total-r.unknown?`${((r.early+r.onTime)/(r.total-r.unknown)*100).toFixed(1)}%`:'—'}</td><td>{Object.entries(r.units).map(([u,n])=>`${u==='g'?Number((n/1000).toFixed(3)):n} ${u==='g'?'kg':u}`).join(' · ')||'—'}</td></tr>)}</tbody></table></div></section>
 </>:<>
 {states[tab]?.length>0&&<div className="factory-state-tabs">{['all',...states[tab]].map(s=><button key={s} className={state===s?'selected':''} onClick={()=>change(setState,s)}>{s==='all'?'Tất cả':factoryStateLabels[s]} <b>{orders.filter(o=>factoryGroup(o)===tab&&(s==='all'||factoryState(o)===s)).length}</b></button>)}</div>}
 <section className="panel"><div className="factory-filters"><label className="field"><span>Tìm kiếm</span><input aria-label="Tìm đơn Xưởng" value={query} onChange={e=>change(setQuery,e.target.value)} placeholder="Mã đơn, Sale, sản phẩm…"/></label><label className="field"><span>Từ ngày</span><input aria-label="Từ ngày" type="date" value={from} onChange={e=>change(setFrom,e.target.value)}/></label><label className="field"><span>Đến ngày</span><input aria-label="Đến ngày" type="date" value={to} onChange={e=>change(setTo,e.target.value)}/></label><label className="field"><span>Hạn gửi từ</span><input type="date" value={dueFrom} onChange={e=>change(setDueFrom,e.target.value)}/></label><label className="field"><span>Hạn gửi đến</span><input type="date" value={dueTo} onChange={e=>change(setDueTo,e.target.value)}/></label><label className="field"><span>{tab==='office'?'Tiến độ giao':'Thời gian còn lại'}</span>{tab==='office'?<select value={timing} onChange={e=>change(setTiming,e.target.value)}><option value="all">Tất cả</option><option value="early">Sớm</option><option value="onTime">Đúng hạn</option><option value="late">Trễ</option><option value="unknown">Thiếu dữ liệu</option></select>:<select value={urgency} onChange={e=>change(setUrgency,e.target.value)}><option value="all">Tất cả</option><option value="overdue">Quá hạn</option><option value="urgent">Còn 0–3 ngày</option></select>}</label><label className="field"><span>Sắp xếp</span><select value={sort} onChange={e=>change(setSort,e.target.value)}><option value="due">Hạn gần nhất</option><option value="newest">Ngày đặt mới nhất</option><option value="oldest">Ngày đặt cũ nhất</option></select></label><button className="btn" onClick={()=>{setQuery('');setFrom('');setTo('');setDueFrom('');setDueTo('');setState('all');setTiming('all');setUrgency('all');setSort('due');setPage(1)}}>Đặt lại</button></div>
 {table(visible)}<div className="pagination"><span>{filtered.length} đơn · Trang {currentPage}/{pages}</span><div><button className="btn" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Trước</button><button className="btn" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Sau</button></div></div>
 {tab!=='office'&&<div className="factory-bulk"><span>Đã chọn {selection.length} đơn</span><button className="btn" disabled={busy||!available} onClick={()=>start('factory-status','producing',selection)}>Ghi nhận / tiếp tục</button><button className="btn" disabled={busy||!available||selection.some(o=>o.stage!==4)} onClick={()=>start('factory-status','paused',selection)}>Tạm dừng</button><button className="btn" disabled={busy||!available||selection.some(o=>o.stage!==4||o.production?.status==='paused')} onClick={()=>start('factory-status','sale_check',selection)}>Gửi Sale Check</button><button className="btn" disabled={busy||!available||selection.some(o=>o.stage!==4||o.production?.status==='paused'||o.saleReview?.result!=='accepted')} onClick={()=>start('factory-office',null,selection)}>Gửi văn phòng</button></div>}
 </section>
 {choice&&<section className="panel panel-body factory-confirm"><h3>{choice.label} · {choice.orders.length} đơn</h3><p>Kiểm tra toàn bộ lựa chọn trước khi xác nhận. Nếu có đơn thay đổi, hãy tải lại và chọn lại.</p><label className="field"><span>Ghi chú chung</span><textarea value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/></label><button className="btn" disabled={busy} onClick={()=>setChoice(null)}>Quay lại</button> <button className="btn primary" disabled={busy} onClick={async()=>{if(await onBatch({...choice,text:note})){setChoice(null);setSelected([])}}}>Xác nhận {choice.orders.length} đơn</button></section>}
 </>}
 </>;
}
