import React,{useState} from 'react';
import {Users,FileText} from '@phosphor-icons/react';
import {groups,steps,today} from '../shared.js';
import {buyerStatistics,customerGroupSeries,openStages} from '../list-statistics.js';
import {displayLabel} from './display-labels.js';
import {AnimatedNumber} from './motion.jsx';
import './list-summaries.css';
const colors=['#de6ba0','#4c91db','#45a584','#d5a537'];
export function CustomerOverview({customers,orders}){
 const [year,setYear]=useState(today().slice(0,4)),[details,setDetails]=useState(false);
 const stats=buyerStatistics(customers,orders),series=customerGroupSeries(customers,year),max=Math.max(1,...series.flatMap(m=>m.values));
 const years=[...new Set([today().slice(0,4),...customers.map(c=>c.created?.slice(0,4)).filter(Boolean)])].sort().reverse();
 return <div className="list-overview customer-overview"><section className="panel group-chart"><div className="panel-head"><div><h3>Biểu đồ tăng giảm khách hàng theo tháng</h3><p>Tổng hồ sơ lũy kế theo 4 nhóm khách hàng</p></div><select aria-label="Năm thống kê khách" value={year} onChange={e=>setYear(e.target.value)}>{years.map(y=><option key={y}>{y}</option>)}</select></div><div className="group-chart-body"><div className="group-chart-legend">{groups.map((g,i)=><span key={g}><i style={{background:colors[i]}}/>{displayLabel(g)}</span>)}</div><div className="group-chart-grid">{series.map(m=><div key={m.month}><div className="group-chart-bars">{m.values.map((v,i)=><div key={i} role="img" tabIndex={0} aria-label={`Tháng ${m.month}: ${v} ${displayLabel(groups[i])}`} title={`Tháng ${m.month} · ${displayLabel(groups[i])}: ${v}`} style={{height:`${v/max*100}%`,minHeight:2,background:colors[i]}}/>)}</div><small>T{m.month}</small></div>)}</div><button className="text-btn" onClick={()=>setDetails(!details)}>{details?'Ẩn bảng số liệu':'Xem bảng số liệu'}</button>{details&&<div className="table-scroll"><table><thead><tr><th>Tháng</th>{groups.map(g=><th key={g}>{displayLabel(g)}</th>)}</tr></thead><tbody>{series.map(m=><tr key={m.month}><td>{m.month}/{year}</td>{m.values.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div>}</div></section>
 <section className="panel buyer-summary" aria-label="Thống kê khách hàng đã mua"><div className="buyer-total"><span className="summary-icon"><Users size={32}/></span><div><h3>Tổng số khách hàng đã mua</h3><strong data-testid="buyers-total"><AnimatedNumber value={stats.total}/></strong><p>{stats.growth===null?'Chưa có khách mua ở tháng trước':`${stats.growth>0?'+':''}${stats.growth}% so với cuối tháng trước`}</p></div></div><div className="buyer-breakdown"><div><span>Khách mới tháng này</span><strong data-testid="buyers-new"><AnimatedNumber value={stats.newCustomers}/></strong></div><div><span>Khách hàng quay lại</span><strong data-testid="buyers-repeat"><AnimatedNumber value={stats.repeat}/></strong></div><div><span>Tỷ lệ khách quay lại</span><strong data-testid="buyers-rate"><AnimatedNumber value={stats.rate}/>%</strong></div></div><p className="summary-note">Khách đã mua: có đơn gửi duyệt. Khách quay lại: có từ 2 đơn gửi duyệt; tỷ lệ = khách quay lại / khách đã mua. Tính đến hôm nay, trong dữ liệu được phép xem.</p></section></div>;
}
export function OpenOrderSummary({orders,onStage,selected}){
 const open=orders.filter(o=>openStages.includes(o.stage));
 return <section className="panel open-order-summary" aria-label="Thống kê đơn chưa hoàn thành"><button className="open-order-total" onClick={()=>onStage('all')} aria-pressed={selected==='all'}><span className="summary-icon"><FileText size={30}/></span><span>Tổng đơn hàng<br/>chưa hoàn thành</span><strong data-testid="open-total"><AnimatedNumber value={open.length}/></strong><small>Đơn đã gửi duyệt · Bước 2–9</small></button><div className="open-stage-list">{openStages.map(stage=><button key={stage} aria-label={`Lọc bước ${stage}: ${displayLabel(steps[stage-1])}`} aria-pressed={selected===String(stage)} onClick={()=>onStage(String(stage))}><i className={`stage-dot stage-dot-${stage}`}/><span>{stage===4?'Đang sản xuất':displayLabel(steps[stage-1])}</span><b data-testid={`stage-count-${stage}`}>{open.filter(o=>o.stage===stage).length}</b></button>)}</div></section>;
}
