import {customerRatio} from '../customer-statistics.js';
import {orderQueues,queueStatistics} from '../order-queue.js';
import React,{useState} from 'react';
import {Users,FileText} from '@phosphor-icons/react';
import {groups,today} from '../shared.js';
import {buyerStatistics,customerGroupSeries} from '../list-statistics.js';
import {displayLabel} from './display-labels.js';
import {AnimatedNumber} from './motion.jsx';
import './list-summaries.css';
const colors=['#de6ba0','#4c91db','#45a584','#d5a537'];
export function CustomerOverview({customers,orders}){
 const [year,setYear]=useState(today().slice(0,4)),[details,setDetails]=useState(false),[month,setMonth]=useState(today().slice(0,7));
 const stats=buyerStatistics(customers,orders,today(),month),series=customerGroupSeries(customers,year),max=Math.max(1,...series.flatMap(m=>m.values));
 const {notReturned,ratio}=customerRatio(stats);
 const ratioText=ratio===null?'—':new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2}).format(ratio);
 const years=[...new Set([today().slice(0,4),...customers.map(c=>c.created?.slice(0,4)).filter(Boolean)])].sort().reverse();
 return <div className="list-overview customer-overview"><section className="panel group-chart"><div className="panel-head"><div><h3>Biểu đồ tăng giảm khách hàng theo tháng</h3><p>Tổng hồ sơ lũy kế theo 4 nhóm khách hàng</p></div><select aria-label="Năm thống kê khách" value={year} onChange={e=>setYear(e.target.value)}>{years.map(y=><option key={y}>{y}</option>)}</select></div><div className="group-chart-body"><div className="group-chart-legend">{groups.map((g,i)=><span key={g}><i style={{background:colors[i]}}/>{displayLabel(g)}</span>)}</div><div className="group-chart-grid">{series.map(m=><div key={m.month}><div className="group-chart-bars">{m.values.map((v,i)=><div key={i} role="img" tabIndex={0} aria-label={`Tháng ${m.month}: ${v} ${displayLabel(groups[i])}`} title={`Tháng ${m.month} · ${displayLabel(groups[i])}: ${v}`} style={{height:`${v/max*100}%`,minHeight:2,background:colors[i]}}/>)}</div><small>T{m.month}</small></div>)}</div><button className="text-btn" onClick={()=>setDetails(!details)}>{details?'Ẩn bảng số liệu':'Xem bảng số liệu'}</button>{details&&<div className="table-scroll"><table><thead><tr><th>Tháng</th>{groups.map(g=><th key={g}>{displayLabel(g)}</th>)}</tr></thead><tbody>{series.map(m=><tr key={m.month}><td>{m.month}/{year}</td>{m.values.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div>}</div></section>
 <section className="panel buyer-summary" aria-label="Thống kê khách hàng đã mua"><div className="buyer-period"><label>Tháng thống kê<input aria-label="Tháng thống kê khách" type="month" value={month} max={today().slice(0,7)} onChange={e=>{if(/^\d{4}-\d{2}$/.test(e.target.value)&&e.target.value<=today().slice(0,7))setMonth(e.target.value)}}/></label><small>{month===today().slice(0,7)?'Cập nhật trong tháng hiện tại':'Số liệu tính đến cuối tháng'}</small></div><div className="buyer-total"><span className="summary-icon"><Users size={32}/></span><div><h3>Tổng số khách hàng đã mua</h3><strong data-testid="buyers-total"><AnimatedNumber value={stats.total}/></strong><p>{stats.growth===null?'Chưa có khách mua ở tháng trước':`${stats.growth>0?'+':''}${stats.growth}% so với cuối tháng trước`}</p></div></div><div className="buyer-breakdown"><div><span>Khách mới trong tháng</span><strong data-testid="buyers-new"><AnimatedNumber value={stats.newCustomers}/></strong></div><div><span>Khách quay lại trong tháng</span><strong data-testid="buyers-repeat"><AnimatedNumber value={stats.repeat}/></strong></div><div><span>Tỷ lệ khách quay lại</span><strong data-testid="buyers-rate"><AnimatedNumber value={stats.rate}/>%</strong></div></div><div className="buyer-comparison" aria-label="So sánh khách mới và khách chưa quay lại"><div><span>Khách chưa quay lại trong tháng</span><strong data-testid="buyers-not-returned">{notReturned}</strong></div><div><span>Khách mới / chưa quay lại</span><strong data-testid="buyers-new-ratio">{ratioText}</strong></div><p data-testid="buyers-ratio-explanation">{ratio===null?'Không có khách chưa quay lại.':`${stats.newCustomers} / ${notReturned} ${Number(ratio.toFixed(2))===ratio?'=':'≈'} ${ratioText} · ${stats.newCustomers} khách mới so với ${notReturned} khách chưa mua lại trong tháng.`}</p><small>Chưa quay lại = khách đã mua − khách quay lại trong tháng, gồm khách mới chưa mua lần hai.</small></div><p className="summary-note">Khách mới: tạo hồ sơ trong tháng và đã có đơn được duyệt. Khách đã mua: có ít nhất 1 đơn được duyệt tính đến tháng đang xem. Khách quay lại: có đơn thứ 2 trở đi được duyệt trong tháng, mỗi khách tính 1 lần/tháng. Tháng mua tính theo lần Kế toán duyệt đầu tiên, giờ Việt Nam. Tỷ lệ = khách quay lại trong tháng / khách đã mua. Chỉ tính dữ liệu được phép xem.</p></section></div>;
}
export function OpenOrderSummary({orders,onStage,selected}){
 const {counts,total}=queueStatistics(orders);
 return <section className="panel open-order-summary" aria-label="Thống kê đơn chưa hoàn thành"><button className="open-order-total" onClick={()=>onStage('all')} aria-pressed={selected==='all'}><span className="summary-icon"><FileText size={30}/></span><span>Hồ sơ<br/>đang xử lý</span><strong data-testid="open-total"><AnimatedNumber value={total}/></strong><small>Theo việc đang chờ xử lý<br/>Mỗi hồ sơ tính một lần</small></button><div className="open-stage-list"><h3 className="queue-title">Đang chờ xử lý</h3>{orderQueues.map(q=><button key={q.key} aria-label={`Lọc: ${q.label}`} aria-pressed={selected==='queue:'+q.key} onClick={()=>onStage('queue:'+q.key)}><i className={`stage-dot stage-dot-${q.stage}`}/><span>{q.label}</span><b data-testid={`queue-count-${q.key}`}>{counts[q.key]}</b></button>)}</div></section>;
}
