import React,{useState,useRef} from 'react';
import {Image,PaperPlaneTilt,X,ArrowSquareOut} from '@phosphor-icons/react';
import {isWorkspace} from './workspace-access.jsx';
import './order-chat.css';
const imageURL=(orderId,id)=>`/api${isWorkspace?'/work':''}/orders/${encodeURIComponent(orderId)}/images/${id}`;
export function OrderChat({order,busy,onSend,Modal,readOnly=false}){
 const [text,setText]=useState(''),[images,setImages]=useState([]),[error,setError]=useState(''),[reading,setReading]=useState(false),[sending,setSending]=useState(false),[preview,setPreview]=useState(null);
 const fileInput=useRef(null),lock=useRef(false);
 const choose=async e=>{
  const files=[...e.target.files];e.target.value='';setError('');if(!files.length)return;
  if(files.length+images.length>4){setError('Mỗi tin nhắn gửi tối đa 4 ảnh.');return}
  if(files.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024)){setError('Chọn JPG, PNG hoặc WebP, tối đa 5 MB/ảnh.');return}
  setReading(true);
  try{const added=await Promise.all(files.map(file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error('Không đọc được ảnh. Vui lòng chọn lại.'));reader.onload=()=>resolve({id:crypto.randomUUID(),name:file.name,data:reader.result});reader.readAsDataURL(file)})));setImages(current=>[...current,...added])}catch(e){setError(e.message)}finally{setReading(false)}
 };
 const send=async e=>{e.preventDefault();if(lock.current||busy||reading||(!text.trim()&&!images.length))return;lock.current=true;setSending(true);setError('');try{const saved=await onSend(order.id,'message',{text,images:images.map(({name,data})=>({name,data}))});if(saved){setText('');setImages([])}else setError('Chưa gửi được. Nội dung và ảnh vẫn được giữ để bạn thử lại.')}catch(e){setError(e.message)}finally{lock.current=false;setSending(false)}};
 return <><div className="messages">{order.messages.length?order.messages.map((m,i)=><div className="message" key={m.id||i}><span className="avatar small pastel">{m.author.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div className="chat-message-content"><b>{m.author} <small>{new Date(m.time).toLocaleString('vi-VN')}</small></b>{m.text&&<p>{m.text}</p>}{!!m.images?.length&&<div className="chat-image-grid">{m.images.map(img=><button type="button" className="chat-image" key={img.id} aria-label={`Xem ảnh ${img.name}`} onClick={()=>setPreview(img)}><img src={imageURL(order.id,img.id)} alt={img.name} loading="lazy"/><span>{img.name}</span></button>)}</div>}</div></div>):<p className="muted">Trao đổi nội dung và ảnh sản phẩm ngay tại đơn này.</p>}</div>
 {!readOnly&&<form className="chat-composer" onSubmit={send}>{images.length>0&&<div className="chat-attachments">{images.map(img=><div className="chat-attachment" key={img.id}><img src={img.data} alt={img.name}/><span>{img.name}</span><button type="button" aria-label={`Bỏ ảnh ${img.name}`} disabled={sending||reading} onClick={()=>setImages(images.filter(x=>x.id!==img.id))}><X size={16}/></button></div>)}</div>}{error&&<p role="alert" className="chat-error">{error}</p>}<div className="message-form"><input aria-label="Nội dung trao đổi" placeholder="Nhập nội dung hoặc gửi ảnh…" maxLength={1000} disabled={sending} value={text} onChange={e=>setText(e.target.value)}/><input hidden ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" multiple aria-label="Chọn ảnh trao đổi" onChange={choose} disabled={sending||reading||busy}/><button type="button" className="btn" disabled={sending||reading||busy||images.length>=4} onClick={()=>fileInput.current.click()}><Image size={18}/>{reading?'Đang đọc…':'Thêm ảnh'}</button><button className="btn primary" disabled={busy||sending||reading||(!text.trim()&&!images.length)}><PaperPlaneTilt size={18}/>{sending?'Đang gửi…':'Gửi'}</button></div><small className="chat-file-hint">JPG, PNG, WebP · Tối đa 5 MB/ảnh · 4 ảnh/tin nhắn</small></form>}
 {preview&&<Modal title={preview.name} wide onClose={()=>setPreview(null)}><div className="chat-lightbox"><img src={imageURL(order.id,preview.id)} alt={preview.name}/><a className="btn" href={imageURL(order.id,preview.id)} target="_blank" rel="noreferrer"><ArrowSquareOut size={18}/>Mở ảnh gốc</a></div></Modal>}</>;
}
