import React from 'react';
import {Trash} from '@phosphor-icons/react';
import {money} from '../shared.js';
import {hairFields,productAmount} from '../product-fields.js';
import './product-table.css';

const Head=({editable=false,showMoney=true})=><thead><tr><th>STT</th><th>Type of hair<br/>extension</th>{hairFields.map(([key,title])=><th key={key}>{title}</th>)}<th>Weight / Qty<br/><small>Grams / đơn vị</small></th>{showMoney&&<><th>Unit price<br/><small>USD/100G hoặc USD/đơn vị</small></th><th>Amount<br/>(USD)</th></>}{editable&&<th/>}</tr></thead>;
export function ProductReadTable({items,showMoney=true}){if(!items.length)return null;return <div className="table-scroll hair-table-scroll" tabIndex={0} aria-label="Thông số sản phẩm"><table className={"hair-table hair-read"+(showMoney?" show-money":"")}><Head showMoney={showMoney}/><tbody>{items.map((p,i)=><tr key={i}><td>{i+1}</td><td><b>{p.name}</b>{p.spec&&<small>{p.spec}</small>}</td>{hairFields.map(([k])=><td key={k}>{p[k]||'—'}</td>)}<td className="hair-weight numeric">{p.qty}<small>{p.priceBasis==='100g'?'Grams':p.unit}</small></td>{showMoney&&<><td className="numeric">{money(p.price)}<small>{p.priceBasis==='100g'?'USD/100G':`USD/${p.unit||'đơn vị'}`}</small></td><td className="hair-amount numeric">{money(productAmount(p))}</td></>}</tr>)}</tbody></table></div>}
export function ProductEditorTable({items,kind,products,onChange,errors={},onTouch=()=>{}}){
 const update=(index,patch)=>onChange(items.map((p,i)=>i===index?{...p,...patch}:p));
 const rows=items.map((p,index)=>({p,index})).filter(({p})=>p.kind===kind);
 return <div className="table-scroll hair-table-scroll" tabIndex={0} aria-label={`Bảng thông số ${kind}`}><table className="hair-table hair-editor"><Head editable/><tbody>{rows.map(({p,index},row)=>{const options=products.filter(x=>!x.kind||x.kind===kind);return <tr key={index}><td>{row+1}</td><td><select aria-label={`Chọn danh mục ${index+1}`} value="" onChange={e=>{const chosen=options[Number(e.target.value)];if(chosen)update(index,{...chosen,productId:chosen.id,kind,price:kind==='gift'?0:chosen.price})}}><option value="">Chọn từ danh mục…</option>{options.map((x,i)=><option key={x.id||i} value={i}>{x.name} · {x.lengthCm?`${x.lengthCm}cm · `:''}{x.color||x.spec||''}</option>)}</select><input aria-label={`Sản phẩm ${index+1}`} value={p.name} maxLength={120} placeholder="Bulk" onChange={e=>update(index,{name:e.target.value})}/>{p.spec&&<input aria-label={`Thông số ${index+1}`} value={p.spec} maxLength={200} onChange={e=>update(index,{spec:e.target.value})}/>}</td>{hairFields.map(([key,,label])=><td key={key}><input aria-label={`${label} ${index+1}`} type={key==='lengthCm'?'number':'text'} min={key==='lengthCm'?'0.1':undefined} max={key==='lengthCm'?300:undefined} step={key==='lengthCm'?'any':undefined} maxLength={200} value={p[key]??''} onChange={e=>update(index,{[key]:e.target.value})}/></td>)}<td className="hair-weight"><input aria-label={`Số lượng ${index+1}`} type="number" min="0" step="any" max="100000" value={p.qty} aria-invalid={!!errors[`qty-${index}`]} onBlur={()=>onTouch(`qty-${index}`)} onChange={e=>update(index,{qty:Number(e.target.value)})}/>{errors[`qty-${index}`]&&<small className="field-error">{errors[`qty-${index}`]}</small>}<input aria-label={`Đơn vị dòng ${index+1}`} value={p.unit} readOnly={p.priceBasis==='100g'} onChange={e=>update(index,{unit:e.target.value})}/></td><td><input aria-label={`Đơn giá ${index+1}`} type="number" min="0" max="100000" step="0.01" disabled={kind==='gift'} value={p.price} aria-invalid={!!errors[`price-${index}`]} onBlur={()=>onTouch(`price-${index}`)} onChange={e=>update(index,{price:Number(e.target.value)})}/><select aria-label={`Cách tính giá ${index+1}`} value={p.priceBasis||'unit'} onChange={e=>update(index,{priceBasis:e.target.value,...(e.target.value==='100g'?{unit:'Gram'}:{})})}><option value="100g">USD/100G</option><option value="unit">USD/đơn vị</option></select>{errors[`price-${index}`]&&<small className="field-error">{errors[`price-${index}`]}</small>}</td><td className="hair-amount numeric">{money(productAmount(p))}</td><td><button className="icon-btn remove" aria-label={`Xóa sản phẩm ${index+1}`} onClick={()=>onChange(items.filter((_,i)=>i!==index))}><Trash size={18}/></button></td></tr>})}</tbody></table>{!rows.length&&<div className="inline-empty">Chưa có sản phẩm trong nhóm này. Bấm “Thêm” để bổ sung.</div>}</div>
}
