import React,{useState,useId} from 'react';
import {ArrowUpRight,ArrowRight,ArrowDownRight,Plus,Receipt,Users,ChartLineUp,Wallet,Clock,Package,NotePencil,CheckCircle,CalendarBlank,CaretRight,MagnifyingGlass,GlobeHemisphereWest,Bell,Command,Question,Tray,Check,StarFour,UserCircle} from '@phosphor-icons/react';
import {totals,money,dateText,status,today} from '../shared.js';

const compact=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
const monthly=(orders,key)=>Array.from({length:9},(_,i)=>orders.filter(o=>o.date?.startsWith(`2026-${String(i+1).padStart(2,'0')}`)).reduce((s,o)=>s+totals(o)[key],0));
const initials=n=>n.split(' ').slice(0,2).map(x=>x[0]).join('');
export function Sparkline({values,color='#32716b'}){const max=Math.max(...values,1),min=Math.min(...values,0);const pts=values.map((v,i)=>`${3+i*12},${32-(v-min)/(max-min||1)*26}`).join(' ');return <svg viewBox="0 0 104 38" className="sparkline" aria-hidden="true"><polyline points={pts} fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/><circle cx="99" cy={32-(values.at(-1)-min)/(max-min||1)*26} r="3" fill={color}/></svg>}
export function KpiStrip({orders,customers}){
 const sum=k=>orders.reduce((s,o)=>s+totals(o)[k],0);const debtOrders=orders.filter(o=>totals(o).debt>0);const customerValues=Array.from({length:9},(_,i)=>customers.filter(c=>c.created?.slice(0,7)<=`2026-${String(i+1).padStart(2,'0')}`).length);
 const specs=[{label:'Doanh thu đơn hàng',value:sum('revenue'),icon:ChartLineUp,key:'revenue',note:`${orders.length} đơn đã ghi nhận`,color:'#d7bb87'}, {label:'Tiền đã xác nhận',value:sum('paid'),icon:Wallet,key:'paid',note:'Đã được Kế toán đối soát',color:'#3b8874'}, {label:'Công nợ hiện tại',value:sum('debt'),icon:Receipt,key:'debt',note:`${debtOrders.length} đơn cần thu hồi`,color:'#c48e4e'}, {label:'Khách hàng',value:customers.length,icon:Users,key:'customers',note:`${new Set(customers.map(c=>c.country)).size} thị trường quốc tế`,color:'#628ac0'}];
 return <div className="metrics refined-metrics">{specs.map((s,i)=><section className={`metric metric-${i}`} key={s.key}><div className="metric-top"><span>{s.label}</span><span className="kpi-icon"><s.icon size={19} weight="duotone"/></span></div><div className="metric-middle"><strong>{i===3?s.value:compact(s.value)}</strong><Sparkline values={i===3?customerValues:monthly(orders,s.key)} color={s.color}/></div><div className="metric-bottom"><span className="kpi-note-dot"/>{s.note}<span>{i===3?'KH':'USD'}</span></div></section>)}</div>
}

export function RevenueChart({orders}){
 const [focus,setFocus]=useState(8);const id=useId().replaceAll(':','');const revenue=monthly(orders,'revenue'),paid=monthly(orders,'paid');const ceiling=Math.max(1000,Math.ceil(Math.max(...revenue,...paid)/2000)*2000);
 const x=i=>54+i*64, y=v=>177-v/ceiling*142;const points=vs=>vs.map((v,i)=>`${x(i)},${y(v)}`).join(' ');const last=revenue[focus],prev=revenue[focus-1];const change=prev?Math.round((last-prev)/prev*100):null;
 return <div className="revenue-visual"><div className="chart-summary"><div><span>Tháng {String(focus+1).padStart(2,'0')} / 2026</span><strong>{money(last)}</strong></div><div className={'chart-change '+(change<0?'negative':'')}>{change!==null?<>{change<0?<ArrowDownRight size={16}/>:<ArrowUpRight size={16}/>} {change>0?'+':''}{change}%<small>so với tháng trước</small></>:<small>Doanh thu đầu kỳ</small>}</div><div className="chart-legend"><span><i/>Doanh thu</span><span><i/>Đã nhận</span></div></div><div className="line-chart"><svg viewBox="0 0 590 218" role="img" aria-label={`Biểu đồ doanh thu 9 tháng, tháng ${focus+1}: ${money(last)}`}><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#5f88c6" stopOpacity=".18"/><stop offset="100%" stopColor="#5f88c6" stopOpacity="0"/></linearGradient></defs>{[0,.25,.5,.75,1].map(v=><g key={v}><line x1="54" y1={y(ceiling*v)} x2="566" y2={y(ceiling*v)} stroke="#e9eef3" strokeDasharray="3 5"/><text x="40" y={y(ceiling*v)+3} textAnchor="end" fontSize="9" fill="#8b98a8">{v===0?'0':`${ceiling*v/1000}k`}</text></g>)}<polygon points={`54,177 ${points(revenue)} 566,177`} fill={`url(#${id})`}/><polyline points={points(paid)} fill="none" stroke="#82b3a0" strokeWidth="2" strokeDasharray="5 5" strokeLinejoin="round"/><polyline points={points(revenue)} fill="none" stroke="#4777be" strokeWidth="2.8" strokeLinecap="round" strokeLinejoin="round"/><line x1={x(focus)} x2={x(focus)} y1="24" y2="177" stroke="#bccbdc" strokeDasharray="3 4"/><circle cx={x(focus)} cy={y(last)} r="7" fill="#fff" stroke="#4777be" strokeWidth="2"/><circle cx={x(focus)} cy={y(last)} r="2.5" fill="#4777be"/>{revenue.map((v,i)=><g key={i}><text x={x(i)} y="205" textAnchor="middle" fontSize="10" fill={i===focus?'#315a93':'#8b98a8'} fontWeight={i===focus?'600':'400'}>T{i+1}</text><rect x={x(i)-25} y="20" width="50" height="192" fill="transparent" role="button" tabIndex="0" aria-label={`Xem doanh thu tháng ${i+1}`} onMouseEnter={()=>setFocus(i)} onFocus={()=>setFocus(i)} onClick={()=>setFocus(i)} onKeyDown={e=>['Enter',' '].includes(e.key)&&setFocus(i)}/></g>)}</svg></div></div>
}

export function PremiumHeader({title,onSearch,onInbox,onGuide,count}){return <header className="topbar"><div className="breadcrumb"><span className="header-workspace">HQ Hair</span><CaretRight size={13}/><strong>{title}</strong></div><div className="top-actions"><button className="global-search" onClick={onSearch}><MagnifyingGlass size={17}/><span>Tìm kiếm nhanh…</span><kbd>Ctrl K</kbd></button><span className="header-demo">Demo</span><button className="header-icon" aria-label="Việc cần chú ý" onClick={onInbox}><Bell size={20}/>{count>0&&<span className="notification-count">{count}</span>}</button><div className="header-separator"/><button className="header-user" onClick={onGuide} aria-label="Hồ sơ Judy"><span className="avatar small">JD</span><span>Judy<small>Sale</small></span></button></div></header>}

export function SearchContent({data,onOrder,onCustomer}){
 const [q,setQ]=useState('');const match=s=>s.toLocaleLowerCase('vi').normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(q.toLocaleLowerCase('vi').normalize('NFD').replace(/[\u0300-\u036f]/g,''));const orders=data.orders.filter(o=>match(`${o.id} ${data.customers.find(c=>c.id===o.customerId)?.name}`)).slice(0,5);const customers=data.customers.filter(c=>match(`${c.id} ${c.name}`)).slice(0,4);
 return <div className="command-content"><div className="command-input"><MagnifyingGlass size={22}/><input autoFocus aria-label="Tìm kiếm toàn hệ thống" placeholder="Tên khách hàng, mã khách hoặc mã đơn…" value={q} onChange={e=>setQ(e.target.value)}/><kbd>ESC</kbd></div><div className="command-results"><h4>ĐƠN HÀNG</h4>{orders.map(o=><button key={o.id} onClick={()=>onOrder(o)}><span className="command-icon"><Receipt size={20}/></span><span><b>{o.id}</b><small>{data.customers.find(c=>c.id===o.customerId)?.name}</small></span><span className="command-status">{status(o)}</span><ArrowUpRight size={17}/></button>)}<h4>KHÁCH HÀNG</h4>{customers.map(c=><button key={c.id} onClick={()=>onCustomer(c)}><span className="avatar pastel">{initials(c.name)}</span><span><b>{c.name}</b><small>{c.id} · {c.company}</small></span><span className="command-status">{c.country}</span><ArrowUpRight size={17}/></button>)}{!orders.length&&!customers.length&&<div className="empty"><MagnifyingGlass size={26}/><h3>Chưa tìm thấy kết quả phù hợp</h3><p>Thử tìm tên hoặc mã khác.</p></div>}</div><div className="command-footer">Tìm nhanh khách hàng và đơn hàng trong không gian của bạn.</div></div>
}
export function InboxContent({data,onOrder}){const items=data.orders.filter(o=>[2,5].includes(o.stage));return <div className="inbox-content">{items.length?items.map(o=><button key={o.id} onClick={()=>onOrder(o)}><span className={`attention-icon ${o.stage===5?'green':'amber'}`}>{o.stage===5?<Package size={22}/>:<Clock size={22}/>}</span><span><b>{o.stage===5?'Xưởng đã hoàn thiện đơn hàng':'Đơn hàng đang chờ duyệt'}</b><p>{o.id} · {data.customers.find(c=>c.id===o.customerId)?.name}</p><small>{o.stage===5?'Kiểm tra và xác nhận tiếp nhận':'Chờ Kế toán đối soát thanh toán'}</small></span><CaretRight size={18}/></button>):<div className="empty"><CheckCircle size={40}/><h3>Bạn đã xử lý hết các việc cần chú ý.</h3></div>}</div>}
