import React from 'react';
import {totals,money,today} from '../shared.js';
export function RevenuePeriodChart({orders,mode,year,month}){
 const keys=mode==='all'?[...new Set([today().slice(0,4),...orders.map(o=>o.date.slice(0,4))])].sort():mode==='year'?Array.from({length:12},(_,i)=>`${year}-${String(i+1).padStart(2,'0')}`):Array.from({length:new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate()},(_,i)=>`${month}-${String(i+1).padStart(2,'0')}`);
 const rows=keys.map(key=>{const items=orders.filter(o=>o.date.startsWith(key));return {key,revenue:items.reduce((n,o)=>n+totals(o).revenue,0),paid:items.reduce((n,o)=>n+totals(o).paid,0)}});
 const max=Math.max(1,...rows.flatMap(r=>[r.revenue,r.paid])),x=i=>50+i*510/Math.max(1,rows.length-1),y=v=>220-v/max*180;
 const label=key=>mode==='all'?key:mode==='year'?'T'+Number(key.slice(5)):String(Number(key.slice(8)));
 return <div className="revenue-visual"><div className="chart-summary"><div><span>{mode==='all'?'Đến hiện tại':mode==='year'?`Năm ${year}`:`Tháng ${month.slice(5)}/${month.slice(0,4)}`}</span><strong>{money(rows.reduce((n,r)=>n+r.revenue,0))}</strong></div><div className="chart-legend"><span><i/>Doanh thu</span><span><i/>Đã nhận</span></div></div><div className="line-chart"><svg viewBox="0 0 590 260" role="img" aria-label="Biểu đồ doanh thu theo kỳ đã chọn">{[0,.25,.5,.75,1].map(v=><g key={v}><line x1="50" x2="560" y1={y(max*v)} y2={y(max*v)} stroke="#e9eef3"/><text x="43" y={y(max*v)+3} textAnchor="end" fontSize="9" fill="#667d91">{Number((max*v).toFixed(0)).toLocaleString('en-US')}</text></g>)}{['revenue','paid'].map((key,k)=><polyline key={key} points={rows.map((r,i)=>`${x(i)},${y(r[key])}`).join(' ')} fill="none" stroke={k?'#82b3a0':'#4777be'} strokeWidth="2.5"/>)}{rows.map((r,i)=><g key={r.key}><circle cx={x(i)} cy={y(r.revenue)} r="3" fill="#4777be"><title>{r.key}: {money(r.revenue)} · Đã nhận {money(r.paid)}</title></circle><text x={x(i)} y="244" textAnchor="middle" fontSize="9" fill="#667d91">{label(r.key)}</text></g>)}</svg></div></div>;
}
